# Excluded directories
excluded:
  - Pods
  - Carthage
  - Generated
  - ReaderIOSTests
  - ReaderIOSUITests

# Disabled rules
disabled_rules:
  - colon
  - comma
  - control_statement
  - todo
  - trailing_comma
  - opening_brace

type_body_length:
  warning: 400 # Warning threshold
  error: 500 # Error threshold

file_length:
  warning: 600 # Warning threshold
  error: 1200 # Error threshold

type_name:
  min_length: 3 # Only warning for minimum length
  max_length:
    warning: 40 # Warning threshold
    error: 50 # Error threshold

identifier_name:
  min_length: # Only minimum length
    warning: 3 # Only error threshold
