# Generated by Django 4.2.5 on 2023-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='e7a78618-f4d7-4ffe-b5a4-2370d1401a15', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
