# Generated by Django 4.2.6 on 2023-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='f8958313-1ae6-4f27-8dfc-957c77f542be', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
