# Generated by Django 4.1 on 2022-08-18 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter_Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('dialect_code', models.CharField(max_length=5)),
                ('title', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptual_difficulty', models.FloatField()),
                ('time_required_mins', models.IntegerField()),
                ('point_value', models.FloatField()),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentapp.chapter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Attachemnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='question_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('dialect_code', models.CharField(max_length=5)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('rubric_text', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('approver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_id', to=settings.AUTH_USER_MODEL)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_id', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptual_difficulty', models.FloatField()),
                ('time_required_mins', models.IntegerField()),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentapp.chapter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('dialect_code', models.CharField(max_length=5)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Rendering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('dialect_code', models.CharField(max_length=5)),
                ('rendering', models.FileField(upload_to='quiz_renderings/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.AddField(
            model_name='quiz_feedback',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.quiz_rendering'),
        ),
        migrations.AddField(
            model_name='question_attachemnt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.question_loc'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentapp.volume'),
        ),
    ]
