# Generated by Django 4.2.5 on 2023-11-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='efea6342-58f3-4eae-bdf9-e08987ecafec', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
