# Generated by Django 4.2.5 on 2023-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0002_chapter_chapter_loc_question_question_attachemnt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longetude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_verified', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('is_quizmaker', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Question_Attachemnt',
            new_name='Question_Attachment',
        ),
    ]
