# Generated by Django 4.2.5 on 2023-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='c484e396-d133-47cb-b61d-8cef7a680616', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
