# Generated by Django 4.2.5 on 2023-11-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='591e9fe9-1e96-4a6c-afbe-d94ecb2e5479', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
