# Generated by Django 4.2.5 on 2023-11-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0003_user_rename_question_attachemnt_question_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longetude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='new_user', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(default='org', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pwd', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_language',
            field=models.CharField(default='language', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='0f99d444-fc98-4adf-a7bb-f51987978353', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='code', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='new_user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_quizmaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('primary_email', models.CharField(default='email', max_length=100, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.user')),
            ],
        ),
    ]
