# Generated by Django 4.2.5 on 2023-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='d00eaa5f-4dde-4cd7-a2e9-8e02c3798ca4', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
