# Generated by Django 4.2.5 on 2023-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='5c78f99a-1f83-4d9a-b1d8-dd50e4682507', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
