# Generated by Django 4.2.5 on 2023-11-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0004_remove_user_id_remove_user_longetude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='c8c77ab1-2988-40f7-8bcf-69307868d0a8', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
