# Generated by Django 4.2.5 on 2023-11-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='bb2a9d10-edcc-46d8-b529-bdbcf5b3701a', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
