# Generated by Django 4.2.5 on 2023-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='59e54331-2f4f-4b32-8e6a-d7a0bd092937', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
