# Generated by Django 4.2.5 on 2023-11-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0005_alter_chapter_chapter_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='336427a3-15a5-4326-81e3-4532952df044', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
