# Generated by Django 4.2.5 on 2023-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='d157dc02-5c29-4a30-a084-f2def4301ff9', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
