# Generated by Django 4.2.5 on 2023-11-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='c4f3ace1-18bf-468e-bce5-5871eccc9a2b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
