# Generated by Django 4.2.5 on 2023-11-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='e2b838b6-4c6a-4fa3-8fe5-982930d1a8bc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
