# Generated by Django 4.2.5 on 2023-11-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='0b8669cc-7cfc-45a3-99ad-4cbee28dddef', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
