# Generated by Django 4.2.6 on 2023-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='ba799c14-dfac-47a2-af01-8864586d32f2', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
