# Generated by Django 4.2.6 on 2023-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0008_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='8f737e50-929f-435f-b83f-06a80ba2f535', editable=False, primary_key=True, serialize=False, unique=True),

        ),
    ]
