# Generated by Django 4.2.5 on 2023-11-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0008_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='1e5aed40-5902-436c-8400-fb77add823cf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
