# Generated by Django 4.2.6 on 2023-11-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0009_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='19ccef9e-5076-43ee-b030-9c537dcdb742', editable=False, primary_key=True, serialize=False, unique=True),

        ),
    ]
