# Generated by Django 4.2.5 on 2023-11-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0009_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='8053be8a-4364-404d-85b5-f6218fcf37a8', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
