# Generated by Django 4.2.5 on 2023-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='07ad7300-ea96-4434-836e-89f12c0b97de', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
