# Generated by Django 4.2.6 on 2023-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='d4073d04-b112-4f5a-868c-efd1ea200158', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
