# Generated by Django 4.2.5 on 2023-11-14 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mentapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('support_id', models.CharField(default='22192bd5-4813-4e69-a432-dbd578785857', editable=False, primary_key=True, serialize=False, verbose_name=mentapp.models.Chapter)),
                ('creator_id', models.CharField(max_length=50, null=True)),
                ('chapter_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='question_attachment',
            old_name='attachment',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='question_attachment',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question_loc',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='quiz_feedback',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.RenameField(
            model_name='quiz_question',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.RenameField(
            model_name='quiz_rendering',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='quiz_feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='question_attachment',
            name='blog_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question_attachment',
            name='dialect_code',
            field=models.CharField(default='US', max_length=5),
        ),
        migrations.AddField(
            model_name='question_attachment',
            name='lang_code',
            field=models.CharField(default='ENG', max_length=5),
        ),
        migrations.AddField(
            model_name='quiz_feedback',
            name='creator_comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz_feedback',
            name='creator_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quiz_feedback',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz_feedback',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz_feedback',
            name='viewer_comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz_feedback',
            name='viewer_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chapter_loc',
            name='dialect_code',
            field=models.CharField(default='US', max_length=5),
        ),
        migrations.AlterField(
            model_name='chapter_loc',
            name='lang_code',
            field=models.CharField(default='ENG', max_length=5),
        ),
        migrations.AlterField(
            model_name='question_loc',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question_loc',
            name='dialect_code',
            field=models.CharField(default='US', max_length=5),
        ),
        migrations.AlterField(
            model_name='question_loc',
            name='lang_code',
            field=models.CharField(default='ENG', max_length=5),
        ),
        migrations.AlterField(
            model_name='quiz_feedback',
            name='dialect_code',
            field=models.CharField(default='US', max_length=5),
        ),
        migrations.AlterField(
            model_name='quiz_feedback',
            name='lang_code',
            field=models.CharField(default='ENG', max_length=5),
        ),
        migrations.AlterField(
            model_name='quiz_rendering',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='6a80e345-ac46-4c0a-957a-e07b70f95d48', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_id', models.CharField(default='verifier', max_length=100)),
                ('verified_id', models.CharField(default='verified', max_length=100)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('date_granted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('verifier_id', 'verified_id')},
            },
        ),
        migrations.CreateModel(
            name='Support_Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(default='ENG', max_length=5)),
                ('dialect_code', models.CharField(default='US', max_length=5)),
                ('title_latex', models.CharField(max_length=100, null=True)),
                ('content_latex', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('creator_id', models.CharField(max_length=50, null=True)),
                ('approver_id', models.CharField(max_length=50, null=True)),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.support')),
            ],
        ),
        migrations.CreateModel(
            name='Support_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('dialect_code', models.CharField(max_length=5)),
                ('filename', models.FileField(upload_to='support_attachments/')),
                ('blog_key', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.question_loc')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.quiz')),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.support')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(default='ENG', max_length=5)),
                ('dialect_code', models.CharField(default='US', max_length=5)),
                ('is_primary', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('handle_id', models.CharField(default='email', max_length=100, primary_key=True, serialize=False)),
                ('site', models.BooleanField(default=False)),
                ('handle', models.CharField(default='handle', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(default='ENG', max_length=5)),
                ('dialect_code', models.CharField(default='US', max_length=5)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=300, null=True)),
                ('creator_id', models.CharField(max_length=50, null=True)),
                ('viewer_id', models.CharField(max_length=50, null=True)),
                ('creator_comment', models.CharField(max_length=300, null=True)),
                ('viewer_comment', models.CharField(max_length=300, null=True)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentapp.chapter')),
            ],
        ),
    ]
