# Generated by Django 4.2.5 on 2023-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0011_remove_user_password_hash_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pwd', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='3eaa8fc8-d43a-4bfe-9ca1-f120f915801e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
