# Generated by Django 4.2.5 on 2023-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0012_user_password_hash_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='0045b637-dd8d-4b38-a5d4-1b3e10c0faee', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
