# Generated by Django 4.2.5 on 2023-11-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0013_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='7bcbf2a2-54a5-4aad-8954-9e0c09e655ea', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
