# Generated by Django 4.2.5 on 2023-11-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentapp', '0014_remove_user_display_name_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='fa664658-4262-4df1-8ffc-fd722b771b41', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
